### ISSUE TITLE
Slides?

### ISSUE THREAD

**Issue by jamesmyatt** [bezhvin/PyData2020-Eindhoven#1]
I watched your talk on YouTube and it was very interesting. Thanks. Are the slides available somewhere? If not, can they be added here, please?

**Comment by bezhvin** [comment]
Hi, Thanks for the interest. I have added the slides:
https://github.com/bezhvin/PyData2020-Eindhoven/blob/main/PyData_missingdata.pdf

**Comment by jamesmyatt** [comment]
Thanks
